#+title: Clojurists Together - Second Report

* Overview
In the second term of this project, I refined and finalised the overall protocol structure for mathematical, representational and predicate operations, particularly confirming the split between what is 'necessary' and what is 'extra' when identifying and manipulating mathematical objects. Using this, I created several more protocols and  implemented more rigorous testing namespaces - involving multiple tiers - and leaning on another Clojurists Together project for generating references: Wolframite. By introducing flexible constructor namespaces for both (real and complex) matrices and numbers, as well as multimethod-based type definitions, I solidified the overall design into a generalised API. Such an API now facilitates different layers of use: allowing for operator overloading, domain promotion and variadic arguments across objects as standard, but leaving the concrete implementations separate and available for when speed really matters.

Overall then, this work completes the funding period, successfully implementing the fastmath matrix protocol for complex matrices and extending this to a generalised API. There is however, still much to do, some of which really has to be done soon for these extensions to be practically useful. Below, I expand on what was done during this period: with a discussion of the overall design, some illustrative examples of the API and a reflection on the overall status and the necessary and hopeful next steps. 


* New Design
Although an enthusiastic consumer of parts of ~fastmath~ previously, it only became apparent to me, in the first part of the project, just how vast the library is. This, combined with the notion that a complex matrix API necessarily requires interaction with complex numbers (and that complex matrix implementation requires a consistent real matrix implementation), naturally led to the need to consider wider interaction problems and so wider design concerns. As highlighted in the midterm report, it became clear that, for the library to continue to expand organically, the implementation details would need to be abstracted, so that we can swap alternative backends in and out more easily in the future. This created contradictions however.

The contradictions arose as the demands for a user-friendly (and consistent) API, orients the solution towards having all of the compatible methods in the same namespace - who wants to import 20 nses to work an a single linear algebra problem? A decomplected (non-hierarchical) protocol structure however, mirrors mathematical implementations well, allows for maximal code reuse and seems to fit with Clojure's design philosophy. Furthermore, some hierarchies are good and necessary and yet these cannot be done using Clojure protocols. My initial attempt in the first term approximated this with aliasing 'lower' (level of abstraction) protocols within higher ones, but trying to balance this with generalised (non implementation dependent) constructors led to cyclical dependencies.

I settled in the end, therefore, for a complete separation of concerns, with protocols expanding modularly in the same way (there are now about 30), the introduction of separate, generalised constructors for numbers and matrices - that worked regardless of domain - and type implementations that were explicitly coupled to underlying libraries.

The 'user friendliness' was then implemented entirely separately using a new, generalised, library-level, version-controlled API that exposes the object protocols and constructors in meaningful ways, but independent of the implementation. This allows the 'backends' to be changed simply by changing the constructor dependencies. On this layer, I then explicitly implemented the linear algebra generalization, using multimethods, such that matrices and numbers can interact consistently, subject to variadic operators, with automatic domain promotion.

It is perhaps also worth mentioning, in addition to practical things like systematic naming conventions (see forthcoming documentation), that in order to integrate the new features with the existing library, I also started to abstract operations outside of the mathematical and physical needs. Fastmath is primarily used within the SciCloj/Noj ecosystem, and so 'representational' protocols were introduced to model matrix access as a two dimensional computing structure (table), rather than a mathematical object. This helps to push the library towards integration with the wider ecosystem, with a long term goal of tighter consistency with tablecloth, tableplot and adjacent libraries.


* New API (and implementations)
Constructors
<-rows extended

general api
- restructured object type definition and query
- domain promotion
- variadic arguments
- full 'add' api for linear algebra
- full 'subtraction' 
- full 'multiplication' 

outer products 

array conversion



* Outlook

experiment in the suitability of Clojure for general mathematics 

As can be seen above, it is now possible to interleave fundamental matrix and numeric operations without overt concern for domain. This is simply scratching the surface of fastmath's potential however. At the end of the first term, it had already become clear that the original scope of the project was too large to be completed within the given timeframe, and so all work had to be done with future extension in mind.  

There are some immediate next steps however, that ideally would already have been completed. These are to coordinate the integration of this branch with generateme, to finalize the optimization and clay documentation and to publicize subsequent performance metrics. I hope to complete these promptly.

Longer



  - wolframite
  - emmy

- far future
  - parallelism

    check todos
    
   as will be detailed in the forthcoming documentation. 
* TODO
** Before submission 
*** decomposition
*** ...dense to fastmath object

** Stretch
*** Fourier
JTransforms
*** derived types
(including square etc.)

* TODO questions
** can types reuse implementations
* Unused
** design
Although the trajectory was set in the first term however, questions like 'Where should the implementation of complex number be?' were soon followed by 'Should protocols represent interface contracts?'

===
how much to change of the existing `fastmath` API

obvious places for future specializations or alternative backends
===

a decomplected and flexible API structure
- problem of hierarcy
- benefit of non-hierarchical protocols


row/column order vs rectangular vs complex

*** Should protocols represent interface contracts?
i.e. If you implement this, your operation works for all inputs of your type?
*** Should `protocol` be a parallel ns branch or in the same folder as the implementations?
*** Similarly to complex number, where should constants like default tolerance be found?
interaction with wider library
*** Do we need a separate matrix and vector namespace?
*** Where should constructors go for key protocols? 
ns branches should only be made at mutually exclusive properties
*** Room for future expansion
**** Would an implementation based on dtype-next be efficient?
[[x y] [x y]]
 [x y] [x y]]
***** I guess all of the operations and decomposition etc. would have to be manually implemented...


** naming conventions
- minimal complectedness
- general to specific
- mathematical
- convention and clarity > speed (perils of shortform)
  - e.g. element vs entry

functions shouldn't have trailing 'm' for matrix everywhere

(m/mul ...) is cleaner than (m/mulm)
namespaces are good!

Should complex matrices come under complex or matrix?
    
'vectors' maintain orientation

Use mathematical notation
Could use this as a general branching point? Multimethod or protocol etc. As opposed to the other methods. 

*** eye ...
This feels like a Python holdover that is not very clear.  Identity or 'I' would probably be better. I do have a sense of humour, honest!

