#+title: Complex Notes

* Proposal
Something is incomplete in Clojure math support... Complex numbers and associated matrices.
** Who am I?
Thomas Clark, a physicist and Clojure hobbyist who is always looking for ways of integrating Clojure into mainstream academia and analysis.

I've most recently worked on and am currently a maintainer of the Wolframite library and I've given a couple of talks regarding this and the scientific state of Clojure.

https://youtu.be/SE5Ge4QP4oY?feature=shared
https://youtu.be/_D5d6Ls6pBw?feature=shared
https://youtu.be/rQ1hpYZSjuY?feature=shared

** What project
fastmath (https://github.com/generateme/fastmath)

** Who is applying?
I am a (minor) collaborator of 'generateme', who is the project owner and main maintainer of fastmath. I have spoken with him and he is interested and willing to help in the extension that I'm proposing but does not want to be part of the application.

** what are you wanting to achieve with this funding?
Inasmuch as Lewis Carrol may have creatively objected, complex numbers are now an essential part of modern life, from quantum computing upwards and whether we are aware of it or not (see the next question!).

Clojure's support for these numbers however, remains sporadic while it's biggest competitor, the well-known comedy snake - and scripting language - (https://www.geeksforgeeks.org/python/history-of-python/), treats complex numbers as first-class citizens.

With this funding I would like to address the issue somewhat, particularly with regard to the implementation of complex matrices, but concerning *a consistent complex API* more generally.

Surveying the current field, the 'emmy' library seems to be the most developed option in this area, but it is focussed on symbolic manipulation. When dealing with large memory simulations, it is unlikely to be competitive. `core.matrix.complex` seems to be the numerical choice but its last commit was 5 years ago, it is a thin wrapper over apache commons and not all matrix protocols seem to have been extended to complex numbers. More confusingly, when dealing with numerical matrices more generally, the go-to choices are fastmath   and neanderthal - neither of which have implemented complex matrices.

As the ecosystem is clearly fragmented, this project would seek to extend fastmath, which is the current high-level go-to for numerical matrices to deal with complex numbers in an API-consistent way.

I would proceed as follows:
- extended *survey* of the status and limitations of the present options (including performance tests for the current implementations)
- *decision* on the best *architecture* for a competitive solution
- *Implementation/API creation* for
  - complex vectors, arrays and fundamental matrix ops (including scaling/trace determinant etc.)
  - LU decomposition and solver
- *Integration* with
  - existing fastmath functions, e.g. including fourier analysis and polynomials
  - Wolframite
  - Clay / kind
- *Performance* comparisons with (at least)
  - Python
  - Emmy
  - Wolframite
- *Publication* of a full blog report, outlining an introduction to working with complex numbers in Clojure, complete with the results and analysis of the above

  The 'stretch' goals would be
  - to ensure full integration of the complex matrix system, such that all current matrix operations in fastmath could be performed seamlessly with complex matrices too.
  - to integrate the implementation with the emmy system, such that operations could be carried out symbolically or numerically as desired
  - to implement the basic operations in neanderthal, for maximum performance



** Why is this project important to the community?
Complex numbers now underpin quantitative life, so whether you are a mathematician, natural scientist or engineer, they come up daily. Even for other types of programmer, complex numbers are the basis of signal (e.g. audio, radar and communications) and image (compression, detection, texture analysis and optics) processing. They now even feature heavily in MRI data and machine learning: extending the user-base to data scientists too.

Such is the case, I hope that this project will both help the community directly and also help contribute to the expansion of the community itself. There is a large section of numerical scientists who are not programmers but who rely on tools like Mathematica and Matlab. Many also use Python, where complex numbers are embedded. These projects are all lacking however, Mathematica and Matlab are not convenient languages for general programming, and so bigger projects, and Python is still, at heart, a scripting language lacking parallelism and REPL interaction. Until Clojure catches up with these however, we will not be able to win over many new users from these fields. A consistent complex API would be a small step, but a necessary one towards this goal.
* Checklist
** API creation
*** fundamental matrix ops
Use fastmath tests
**** add 
**** subtract
**** add scalar
**** scale
**** norm
**** inner product
**** outer product
**** multiply
**** TODO multiply elements
check this

*** easy interoperability?
*** TODO LU decomposition and solver
check
** Integration
*** real and complex
interoperability
** postponed
*** fixed size matrices (efficiency)
*** Ince-Gaussian
*** Fourier-analysis
*** Wolframite
*** Performance comparison
(at least one of)
**** Python
**** Wolframite

*** clay doc
*** initial performance tests 
**** TODO fastmath (non complex)
vs Python
**** TODO run java matrix benchmark test
main considerations: ejml vs ojalgo

*** communication
**** post on reddit etc. for ideas
*** Implementation
**** TODO ojalgo?


* Previous/current API
** implementation
Fastmath uses a mixture of apache and hard-coded clojure?
* API ideas
** matrix
*** separation of concerns
protocol.matrix
    structure
        square
        rectangular

    (not mutually exclusive) property 
        symmetric
        Hermitian
        triangular
        diagonal
        positive-definite
        orthogonal / unitary
 
    representation
        dense
        sparse
            csr
            csc
            coo
        banded
        block
    scalar
        real
        complex
        rational
        integer
* Future
** Parallel options available
ejml methods
ojalg?
** Docs
*** implementation choices 
Row, column order should probably be specified somewhere.
*** naming conventions
General pattern should be made explicit, i.e.
general-specialised-maths-representation-implementation...

**** Should 'm' be replaced with 'M' as the standard placeholder?

*** API
**** should we branch on 'complex' right at the start?
i.e. ...matrix.dense.complex.ejml
or ...complex.matrix.dense.ejml
**** Should the impementation be high or low in the API?
i.e. matrix.complex.ejml.dense or complex.matrix.dense.ejml

thinking at the bottom so that the API is conceptual. 

** implementation on Neanderthal?
** implicit matrix/vector construction
e.g. (* [1 2 3] [4 5 6]) becomes matrixy 

** FAQ
*** state of core.matrix?
dead!

*** Where can we store the type?

*** How are complex numbers implemented?
(currently two ways)
Needs to play nicely with `Complex_F64` for `EJML`

would be nice not to have to do this

* Resources
- Java Matrix Benchmark (https://github.com/lessthanoptimal/Java-Matrix-Benchmark)
- netlib (for BLAS operations) (https://github.com/luhenry/netlib)
- hipparchus is the replacement for apache commons math? (https://github.com/Hipparchus-Math/hipparchus)
- 'fastest' java matrix library?! (https://github.com/optimatika/ojAlgo)

  Confusing complex number support. Probably doesn't do matrix multiplication. 
  -    This was wrong. Does do complex matrices, but found a bug.
  - might be a good default for real operations?

** libraries available
https://github.com/lsolbach/qclojure/blob/math-refactoring/src/org/soulspace/qclojure/domain/math/clojure_math.clj

https://github.com/lessthanoptimal/ejml

https://github.com/jblas-project/jblas
- considered but weird dependencies

apache commons field matrix?
and complex (field?) vectors

compare and make a decision

*** Transform support
- fft4j
* Unused
** naming conventions
This is cleaner and more universal, e.g. (m/*v) instead of (m/mulv)
** api
*** vtmul
Argument order is strange?

*** separate creation functions?
e.g. diag and diagonal 
one is information retrieval; other is creation
names very similar 

Maybe have (m/diag A) and

(m.create/diag [...])
(m.new/diag [...])
(mc/diag [...])

*** Can't use 'vectors' as 'vector'!
Clojure vectors ([...]) can't be used with mulv.
