(ns fastmath.api.v1.matrix
  "Backwards-compatible matrix operations.")

(def entry [m row col])
(def ->seq [m])
(def fmap [m f])
(def cols [m])
(def rows [m])
(def to-float-array2d [m])
(def to-double-array2d [m])
(def to-float-array [m])
(def to-double-array [m])
(def to-real-matrix [m])
(def nrow [m])
(def ncol [m])
(def column [m id])
(def row [m id])
(def symmetric? [m] [m tol])
(def transpose [m])
(def inverse [m])
(def diag [m])
(def det [m])
(def add [m1 m2])
(def adds [m v])
(def sub [m] [m1 m2])
(def emulm [m1 m2])
(def mulm [m1 m2] [m1 t1? m2 t2?])
(def mulv [m v])
(def vtmul [m v])
(def muls [m v])
(def trace [m])
(def cholesky [m])
(def norm [m t])
(def singular? [m])
(def solve [m v])

;; MatrixDecomposition
(def component [m c])
